// <auto-generated />
using System;
using BuildCongRenLuyen.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuildCongRenLuyen.Migrations
{
    [DbContext(typeof(MyDBContext))]
    partial class MyDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BuildCongRenLuyen.Models.Kdmadmin", b =>
                {
                    b.Property<long>("Idadmin")
                        .HasColumnType("bigint")
                        .HasColumnName("IDAdmin");

                    b.Property<string>("AdminPassword")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Username")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Idadmin")
                        .HasName("PK__KDMAdmin__D704F3E8E9F8F627");

                    b.ToTable("KDMAdmin", (string)null);
                });

            modelBuilder.Entity("BuildCongRenLuyen.Models.Kdmbh", b =>
                {
                    b.Property<long>("Idbh")
                        .HasColumnType("bigint")
                        .HasColumnName("IDBH");

                    b.Property<string>("MaBh")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("MaBH");

                    b.Property<string>("TenBh")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("TenBH");

                    b.HasKey("Idbh")
                        .HasName("PK__KDMBH__B87DA8DFF202D611");

                    b.ToTable("KDMBH", (string)null);
                });

            modelBuilder.Entity("BuildCongRenLuyen.Models.KdmbhngChng", b =>
                {
                    b.Property<long>("IdbhngChng")
                        .HasColumnType("bigint")
                        .HasColumnName("IDBHNgChng");

                    b.Property<long>("Idbh")
                        .HasColumnType("bigint")
                        .HasColumnName("IDBH");

                    b.Property<long>("Idngh")
                        .HasColumnType("bigint")
                        .HasColumnName("IDNgh");

                    b.Property<string>("MaBhngChng")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("MaBHNgCHNg");

                    b.HasKey("IdbhngChng")
                        .HasName("PK__KDMBHNgC__9B0F5EE55F482341");

                    b.HasIndex("Idbh");

                    b.HasIndex("Idngh");

                    b.ToTable("KDMBHNgCHNG", (string)null);
                });

            modelBuilder.Entity("BuildCongRenLuyen.Models.KdmduLieuHdnk", b =>
                {
                    b.Property<long>("Idbachenganh")
                        .HasColumnType("bigint")
                        .HasColumnName("IDBACHENGANH");

                    b.Property<int>("DiemHdnk")
                        .HasColumnType("int")
                        .HasColumnName("DiemHDNK");

                    b.Property<long>("Idhdnk")
                        .HasColumnType("bigint")
                        .HasColumnName("IDHDNK");

                    b.Property<long>("Idnhhk")
                        .HasColumnType("bigint")
                        .HasColumnName("IDNHHK");

                    b.HasKey("Idbachenganh")
                        .HasName("PK__KDMDuLie__50DAAC3372A2535E");

                    b.HasIndex("Idhdnk");

                    b.HasIndex("Idnhhk");

                    b.ToTable("KDMDuLieuHDNK", (string)null);
                });

            modelBuilder.Entity("BuildCongRenLuyen.Models.Kdmhdnk", b =>
                {
                    b.Property<long>("Idhdnk")
                        .HasColumnType("bigint")
                        .HasColumnName("IDHDNK");

                    b.Property<int>("Diemhdnk")
                        .HasColumnType("int")
                        .HasColumnName("DIEMHDNK");

                    b.Property<long?>("IdquyDinhh")
                        .HasColumnType("bigint")
                        .HasColumnName("IDQuyDinhh");

                    b.Property<string>("MaHdnk")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("MaHDNK");

                    b.Property<string>("TenHdnk")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("TenHDNK");

                    b.HasKey("Idhdnk")
                        .HasName("PK__KDMHDNK__F8B3F945990D9C4F");

                    b.HasIndex("IdquyDinhh");

                    b.ToTable("KDMHDNK", (string)null);
                });

            modelBuilder.Entity("BuildCongRenLuyen.Models.KdmlichDangKy", b =>
                {
                    b.Property<long>("IdlichDangKy")
                        .HasColumnType("bigint")
                        .HasColumnName("IDLichDangKy");

                    b.Property<long?>("Idlop")
                        .HasColumnType("bigint")
                        .HasColumnName("IDLop");

                    b.Property<long?>("Idnhhk")
                        .HasColumnType("bigint")
                        .HasColumnName("IDNHHK");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime");

                    b.HasKey("IdlichDangKy")
                        .HasName("PK__KDMLichD__AB444BD50A72A25D");

                    b.HasIndex("Idlop");

                    b.HasIndex("Idnhhk");

                    b.ToTable("KDMLichDangKy", (string)null);
                });

            modelBuilder.Entity("BuildCongRenLuyen.Models.Kdmngh", b =>
                {
                    b.Property<long>("Idngh")
                        .HasColumnType("bigint")
                        .HasColumnName("IDNgh");

                    b.Property<long>("Idkhoa")
                        .HasColumnType("bigint")
                        .HasColumnName("IDKhoa");

                    b.Property<string>("MaNgh")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenNgh")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Idngh")
                        .HasName("PK__KDMNgh__94587EB3D10A7BA2");

                    b.HasIndex("Idkhoa");

                    b.ToTable("KDMNgh", (string)null);
                });

            modelBuilder.Entity("BuildCongRenLuyen.Models.Kdmnhhk", b =>
                {
                    b.Property<long>("Idnhhk")
                        .HasColumnType("bigint")
                        .HasColumnName("IDNHHK");

                    b.Property<string>("MaNhhk")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("MaNHHK");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime");

                    b.Property<int>("SoTuanHk")
                        .HasColumnType("int")
                        .HasColumnName("SoTuanHK");

                    b.Property<string>("TenNhhk")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("TenNHHK");

                    b.Property<int>("TuanBatDau")
                        .HasColumnType("int");

                    b.HasKey("Idnhhk")
                        .HasName("PK__KDMNHHK__3D13F817AFE82D19");

                    b.ToTable("KDMNHHK", (string)null);
                });

            modelBuilder.Entity("BuildCongRenLuyen.Models.KdmquyDinh", b =>
                {
                    b.Property<long>("IdquyDinh")
                        .HasColumnType("bigint")
                        .HasColumnName("IDQuyDinh");

                    b.Property<long?>("IdvanBan")
                        .HasColumnType("bigint")
                        .HasColumnName("IDVanBan");

                    b.Property<string>("MaQuyDinh")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("IdquyDinh")
                        .HasName("PK__KDMQuyDi__3DB7A295AFF6F1FB");

                    b.HasIndex("IdvanBan");

                    b.ToTable("KDMQuyDinh", (string)null);
                });

            modelBuilder.Entity("BuildCongRenLuyen.Models.Kdmtthdnk", b =>
                {
                    b.Property<long>("Idtthdnk")
                        .HasColumnType("bigint")
                        .HasColumnName("IDTTHDNK");

                    b.Property<string>("BuoiUuTien")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<long?>("IddiaDiem")
                        .HasColumnType("bigint")
                        .HasColumnName("IDDiaDiem");

                    b.Property<long>("IdgiangVien")
                        .HasColumnType("bigint")
                        .HasColumnName("IDGiangVien");

                    b.Property<long>("Idhdnk")
                        .HasColumnType("bigint")
                        .HasColumnName("IDHDNK");

                    b.Property<long>("Idkhoa")
                        .HasColumnType("bigint")
                        .HasColumnName("IDKhoa");

                    b.Property<long?>("Idphong")
                        .HasColumnType("bigint")
                        .HasColumnName("IDPhong");

                    b.Property<bool>("IsCanPhong")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayBđ")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayBĐ");

                    b.Property<DateTime?>("NgayKt")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayKT");

                    b.Property<string>("PhamVi")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("SoLuongDuKien")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongThucTe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<DateTime?>("ThoiLuongToChuc")
                        .HasColumnType("datetime");

                    b.HasKey("Idtthdnk")
                        .HasName("PK__KDMTTHDN__42367C9F58AB298D");

                    b.HasIndex("IddiaDiem");

                    b.HasIndex("IdgiangVien");

                    b.HasIndex("Idhdnk");

                    b.HasIndex("Idkhoa");

                    b.HasIndex("Idphong");

                    b.ToTable("KDMTTHDNK", (string)null);
                });

            modelBuilder.Entity("BuildCongRenLuyen.Models.KdmvanBan", b =>
                {
                    b.Property<long>("IdvanBan")
                        .HasColumnType("bigint")
                        .HasColumnName("IDVanBan");

                    b.Property<string>("Link")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("MaVanBan")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TenVanBan")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("IdvanBan")
                        .HasName("PK__KDMVanBa__FDADF58B9C109449");

                    b.ToTable("KDMVanBan", (string)null);
                });

            modelBuilder.Entity("BuildCongRenLuyen.Models.Kkqsvdkhdnk", b =>
                {
                    b.Property<long>("IddangKy")
                        .HasColumnType("bigint")
                        .HasColumnName("IDDangKy");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<long>("IdgiangVien")
                        .HasColumnType("bigint")
                        .HasColumnName("IDGiangVien");

                    b.Property<long>("Idhdnk")
                        .HasColumnType("bigint")
                        .HasColumnName("IDHDNK");

                    b.Property<long>("IdsinhVien")
                        .HasColumnType("bigint")
                        .HasColumnName("IDSinhVien");

                    b.Property<bool?>("IsThamGia")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NgayDuyet")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayLap")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayThamGia")
                        .HasColumnType("datetime");

                    b.Property<int?>("SoDiem")
                        .HasColumnType("int");

                    b.Property<bool?>("TinhTrangDuyet")
                        .HasColumnType("bit");

                    b.HasKey("IddangKy")
                        .HasName("PK__KKQSVDKH__73566083A3A67D58");

                    b.HasIndex("IdgiangVien");

                    b.HasIndex("Idhdnk");

                    b.HasIndex("IdsinhVien");

                    b.ToTable("KKQSVDKHDNK", (string)null);
                });

            modelBuilder.Entity("BuildCongRenLuyen.Models.NdmgiangVien", b =>
                {
                    b.Property<long>("IdgiangVien")
                        .HasColumnType("bigint")
                        .HasColumnName("IDGiangVien");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("Idkhoa")
                        .HasColumnType("bigint")
                        .HasColumnName("IDKhoa");

                    b.Property<string>("MaNv")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("MaNV");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime");

                    b.Property<bool>("Phai")
                        .HasColumnType("bit");

                    b.Property<string>("ThongTinLienHe")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdgiangVien")
                        .HasName("PK__NDMGiang__EA9BCA1C66420B56");

                    b.HasIndex("Idkhoa");

                    b.ToTable("NDMGiangVien", (string)null);
                });

            modelBuilder.Entity("BuildCongRenLuyen.Models.Ndmkhoa", b =>
                {
                    b.Property<long>("Idkhoa")
                        .HasColumnType("bigint")
                        .HasColumnName("IDKhoa");

                    b.Property<string>("MaKhoa")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Idkhoa")
                        .HasName("PK__NDMKhoa__1AB42731FF4CDE09");

                    b.ToTable("NDMKhoa", (string)null);
                });

            modelBuilder.Entity("BuildCongRenLuyen.Models.PdmdiaDiem", b =>
                {
                    b.Property<long>("IddiaDiem")
                        .HasColumnType("bigint")
                        .HasColumnName("IDDiaDiem");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TenDiaDiem")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("IddiaDiem")
                        .HasName("PK__PDMDiaDi__3DD0D654487162A5");

                    b.ToTable("PDMDiaDiem", (string)null);
                });

            modelBuilder.Entity("BuildCongRenLuyen.Models.Pdmphong", b =>
                {
                    b.Property<long>("Idphong")
                        .HasColumnType("bigint")
                        .HasColumnName("IDPhong");

                    b.Property<string>("CoSo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DayPhong")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DienTichSuDung")
                        .HasColumnType("int");

                    b.Property<long>("IddiaDiem")
                        .HasColumnType("bigint")
                        .HasColumnName("IDDiaDiem");

                    b.Property<string>("MaPhong")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("SucChua")
                        .HasColumnType("int");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TinhChatPhong")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Idphong")
                        .HasName("PK__PDMPhong__81CB1152B796B54E");

                    b.HasIndex("IddiaDiem");

                    b.ToTable("PDMPhong", (string)null);
                });

            modelBuilder.Entity("BuildCongRenLuyen.Models.Sdmlop", b =>
                {
                    b.Property<long>("Idlop")
                        .HasColumnType("bigint")
                        .HasColumnName("IDLop");

                    b.Property<long>("IdbhngChng")
                        .HasColumnType("bigint")
                        .HasColumnName("IDBHNgCHNg");

                    b.Property<long>("Idkhoa")
                        .HasColumnType("bigint")
                        .HasColumnName("IDKhoa");

                    b.Property<string>("MaLop")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NamVao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Idlop")
                        .HasName("PK__SDMLop__95D0020390EBA9B9");

                    b.HasIndex("IdbhngChng");

                    b.HasIndex("Idkhoa");

                    b.ToTable("SDMLop", (string)null);
                });

            modelBuilder.Entity("BuildCongRenLuyen.Models.Sdmsv", b =>
                {
                    b.Property<long>("IdsinhVien")
                        .HasColumnType("bigint")
                        .HasColumnName("IDSinhVien");

                    b.Property<string>("HoTenSinhVien")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("IdgiangVien")
                        .HasColumnType("bigint")
                        .HasColumnName("IDGiangVien");

                    b.Property<long>("Idlop")
                        .HasColumnType("bigint")
                        .HasColumnName("IDLop");

                    b.Property<long>("Idnhhk")
                        .HasColumnType("bigint")
                        .HasColumnName("IDNHHK");

                    b.Property<bool>("IsBanCanSu")
                        .HasColumnType("bit");

                    b.Property<string>("MaSinhVien")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime");

                    b.Property<bool>("Phai")
                        .HasColumnType("bit");

                    b.Property<string>("TrangThaiSinhVien")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("IdsinhVien")
                        .HasName("PK__SDMSV__9015D5B30B55CBD2");

                    b.HasIndex("IdgiangVien");

                    b.HasIndex("Idlop");

                    b.HasIndex("Idnhhk");

                    b.ToTable("SDMSV", (string)null);
                });

            modelBuilder.Entity("BuildCongRenLuyen.Models.KdmbhngChng", b =>
                {
                    b.HasOne("BuildCongRenLuyen.Models.Kdmbh", "IdbhNavigation")
                        .WithMany("KdmbhngChngs")
                        .HasForeignKey("Idbh")
                        .IsRequired()
                        .HasConstraintName("FK_KDMNHNgCHNG_KDMBH");

                    b.HasOne("BuildCongRenLuyen.Models.Kdmngh", "IdnghNavigation")
                        .WithMany("KdmbhngChngs")
                        .HasForeignKey("Idngh")
                        .IsRequired()
                        .HasConstraintName("FK_KDMNHNgCHNG_KDMNgh");

                    b.Navigation("IdbhNavigation");

                    b.Navigation("IdnghNavigation");
                });

            modelBuilder.Entity("BuildCongRenLuyen.Models.KdmduLieuHdnk", b =>
                {
                    b.HasOne("BuildCongRenLuyen.Models.Kdmhdnk", "IdhdnkNavigation")
                        .WithMany("KdmduLieuHdnks")
                        .HasForeignKey("Idhdnk")
                        .IsRequired()
                        .HasConstraintName("FK_KDMHDNK_DULIEU_HDNK");

                    b.HasOne("BuildCongRenLuyen.Models.Kdmnhhk", "IdnhhkNavigation")
                        .WithMany("KdmduLieuHdnks")
                        .HasForeignKey("Idnhhk")
                        .IsRequired()
                        .HasConstraintName("FK_NHHK_DULIEU_HDNK");

                    b.Navigation("IdhdnkNavigation");

                    b.Navigation("IdnhhkNavigation");
                });

            modelBuilder.Entity("BuildCongRenLuyen.Models.Kdmhdnk", b =>
                {
                    b.HasOne("BuildCongRenLuyen.Models.KdmquyDinh", "IdquyDinhhNavigation")
                        .WithMany("Kdmhdnks")
                        .HasForeignKey("IdquyDinhh")
                        .HasConstraintName("FK_KDMHDNK_KDMQUYDINHH");

                    b.Navigation("IdquyDinhhNavigation");
                });

            modelBuilder.Entity("BuildCongRenLuyen.Models.KdmlichDangKy", b =>
                {
                    b.HasOne("BuildCongRenLuyen.Models.Sdmlop", "IdlopNavigation")
                        .WithMany("KdmlichDangKies")
                        .HasForeignKey("Idlop")
                        .HasConstraintName("FK_KDMLichDangKy_KDMLop");

                    b.HasOne("BuildCongRenLuyen.Models.Kdmnhhk", "IdnhhkNavigation")
                        .WithMany("KdmlichDangKies")
                        .HasForeignKey("Idnhhk")
                        .HasConstraintName("FK_KDMLichDangKy_KDMNHHK");

                    b.Navigation("IdlopNavigation");

                    b.Navigation("IdnhhkNavigation");
                });

            modelBuilder.Entity("BuildCongRenLuyen.Models.Kdmngh", b =>
                {
                    b.HasOne("BuildCongRenLuyen.Models.Ndmkhoa", "IdkhoaNavigation")
                        .WithMany("Kdmnghs")
                        .HasForeignKey("Idkhoa")
                        .IsRequired()
                        .HasConstraintName("FK_KDMNgh_NDMKHOA");

                    b.Navigation("IdkhoaNavigation");
                });

            modelBuilder.Entity("BuildCongRenLuyen.Models.KdmquyDinh", b =>
                {
                    b.HasOne("BuildCongRenLuyen.Models.KdmvanBan", "IdvanBanNavigation")
                        .WithMany("KdmquyDinhs")
                        .HasForeignKey("IdvanBan")
                        .HasConstraintName("FK_KDMHDNK_KDMQUYDINH");

                    b.Navigation("IdvanBanNavigation");
                });

            modelBuilder.Entity("BuildCongRenLuyen.Models.Kdmtthdnk", b =>
                {
                    b.HasOne("BuildCongRenLuyen.Models.PdmdiaDiem", "IddiaDiemNavigation")
                        .WithMany("Kdmtthdnks")
                        .HasForeignKey("IddiaDiem")
                        .HasConstraintName("FK_TTHDNK_PDMDIADIEM");

                    b.HasOne("BuildCongRenLuyen.Models.NdmgiangVien", "IdgiangVienNavigation")
                        .WithMany("Kdmtthdnks")
                        .HasForeignKey("IdgiangVien")
                        .IsRequired()
                        .HasConstraintName("FK_TTHDNK_NDMGiangVien");

                    b.HasOne("BuildCongRenLuyen.Models.Kdmhdnk", "IdhdnkNavigation")
                        .WithMany("Kdmtthdnks")
                        .HasForeignKey("Idhdnk")
                        .IsRequired()
                        .HasConstraintName("FK_TTHDNK_KDMHDNK");

                    b.HasOne("BuildCongRenLuyen.Models.Ndmkhoa", "IdkhoaNavigation")
                        .WithMany("Kdmtthdnks")
                        .HasForeignKey("Idkhoa")
                        .IsRequired()
                        .HasConstraintName("FK_TTHDNK_Khoa");

                    b.HasOne("BuildCongRenLuyen.Models.Pdmphong", "IdphongNavigation")
                        .WithMany("Kdmtthdnks")
                        .HasForeignKey("Idphong")
                        .HasConstraintName("FK_TTHDNK_PDMPHONG");

                    b.Navigation("IddiaDiemNavigation");

                    b.Navigation("IdgiangVienNavigation");

                    b.Navigation("IdhdnkNavigation");

                    b.Navigation("IdkhoaNavigation");

                    b.Navigation("IdphongNavigation");
                });

            modelBuilder.Entity("BuildCongRenLuyen.Models.Kkqsvdkhdnk", b =>
                {
                    b.HasOne("BuildCongRenLuyen.Models.NdmgiangVien", "IdgiangVienNavigation")
                        .WithMany("Kkqsvdkhdnks")
                        .HasForeignKey("IdgiangVien")
                        .IsRequired()
                        .HasConstraintName("FK_HDNK_LIENKET_GIANGVIEN");

                    b.HasOne("BuildCongRenLuyen.Models.Kdmhdnk", "IdhdnkNavigation")
                        .WithMany("Kkqsvdkhdnks")
                        .HasForeignKey("Idhdnk")
                        .IsRequired()
                        .HasConstraintName("FK_HDNK_LIENKET_SV");

                    b.HasOne("BuildCongRenLuyen.Models.Sdmsv", "IdsinhVienNavigation")
                        .WithMany("Kkqsvdkhdnks")
                        .HasForeignKey("IdsinhVien")
                        .IsRequired()
                        .HasConstraintName("FK_SV_LIENKET_HDNK");

                    b.Navigation("IdgiangVienNavigation");

                    b.Navigation("IdhdnkNavigation");

                    b.Navigation("IdsinhVienNavigation");
                });

            modelBuilder.Entity("BuildCongRenLuyen.Models.NdmgiangVien", b =>
                {
                    b.HasOne("BuildCongRenLuyen.Models.Ndmkhoa", "IdkhoaNavigation")
                        .WithMany("NdmgiangViens")
                        .HasForeignKey("Idkhoa")
                        .IsRequired()
                        .HasConstraintName("FK_NDMGIANGVIEN_NDMKHOA");

                    b.Navigation("IdkhoaNavigation");
                });

            modelBuilder.Entity("BuildCongRenLuyen.Models.Pdmphong", b =>
                {
                    b.HasOne("BuildCongRenLuyen.Models.PdmdiaDiem", "IddiaDiemNavigation")
                        .WithMany("Pdmphongs")
                        .HasForeignKey("IddiaDiem")
                        .IsRequired()
                        .HasConstraintName("FK_PDMPHONG_PDMDIADIEM");

                    b.Navigation("IddiaDiemNavigation");
                });

            modelBuilder.Entity("BuildCongRenLuyen.Models.Sdmlop", b =>
                {
                    b.HasOne("BuildCongRenLuyen.Models.KdmbhngChng", "IdbhngChngNavigation")
                        .WithMany("Sdmlops")
                        .HasForeignKey("IdbhngChng")
                        .IsRequired()
                        .HasConstraintName("FK_KDMNHNgCHNG_DULIEU_SDMLOP");

                    b.HasOne("BuildCongRenLuyen.Models.Ndmkhoa", "IdkhoaNavigation")
                        .WithMany("Sdmlops")
                        .HasForeignKey("Idkhoa")
                        .IsRequired()
                        .HasConstraintName("FK_NDMKHOA_SDMLOP");

                    b.Navigation("IdbhngChngNavigation");

                    b.Navigation("IdkhoaNavigation");
                });

            modelBuilder.Entity("BuildCongRenLuyen.Models.Sdmsv", b =>
                {
                    b.HasOne("BuildCongRenLuyen.Models.NdmgiangVien", "IdgiangVienNavigation")
                        .WithMany("Sdmsvs")
                        .HasForeignKey("IdgiangVien")
                        .IsRequired()
                        .HasConstraintName("FK_SDMSV_NDMGiangVien");

                    b.HasOne("BuildCongRenLuyen.Models.Sdmlop", "IdlopNavigation")
                        .WithMany("Sdmsvs")
                        .HasForeignKey("Idlop")
                        .IsRequired()
                        .HasConstraintName("FK_SDMSV_SDMLOP");

                    b.HasOne("BuildCongRenLuyen.Models.Kdmnhhk", "IdnhhkNavigation")
                        .WithMany("Sdmsvs")
                        .HasForeignKey("Idnhhk")
                        .IsRequired()
                        .HasConstraintName("FK_SDMSV_NHHK");

                    b.Navigation("IdgiangVienNavigation");

                    b.Navigation("IdlopNavigation");

                    b.Navigation("IdnhhkNavigation");
                });

            modelBuilder.Entity("BuildCongRenLuyen.Models.Kdmbh", b =>
                {
                    b.Navigation("KdmbhngChngs");
                });

            modelBuilder.Entity("BuildCongRenLuyen.Models.KdmbhngChng", b =>
                {
                    b.Navigation("Sdmlops");
                });

            modelBuilder.Entity("BuildCongRenLuyen.Models.Kdmhdnk", b =>
                {
                    b.Navigation("KdmduLieuHdnks");

                    b.Navigation("Kdmtthdnks");

                    b.Navigation("Kkqsvdkhdnks");
                });

            modelBuilder.Entity("BuildCongRenLuyen.Models.Kdmngh", b =>
                {
                    b.Navigation("KdmbhngChngs");
                });

            modelBuilder.Entity("BuildCongRenLuyen.Models.Kdmnhhk", b =>
                {
                    b.Navigation("KdmduLieuHdnks");

                    b.Navigation("KdmlichDangKies");

                    b.Navigation("Sdmsvs");
                });

            modelBuilder.Entity("BuildCongRenLuyen.Models.KdmquyDinh", b =>
                {
                    b.Navigation("Kdmhdnks");
                });

            modelBuilder.Entity("BuildCongRenLuyen.Models.KdmvanBan", b =>
                {
                    b.Navigation("KdmquyDinhs");
                });

            modelBuilder.Entity("BuildCongRenLuyen.Models.NdmgiangVien", b =>
                {
                    b.Navigation("Kdmtthdnks");

                    b.Navigation("Kkqsvdkhdnks");

                    b.Navigation("Sdmsvs");
                });

            modelBuilder.Entity("BuildCongRenLuyen.Models.Ndmkhoa", b =>
                {
                    b.Navigation("Kdmnghs");

                    b.Navigation("Kdmtthdnks");

                    b.Navigation("NdmgiangViens");

                    b.Navigation("Sdmlops");
                });

            modelBuilder.Entity("BuildCongRenLuyen.Models.PdmdiaDiem", b =>
                {
                    b.Navigation("Kdmtthdnks");

                    b.Navigation("Pdmphongs");
                });

            modelBuilder.Entity("BuildCongRenLuyen.Models.Pdmphong", b =>
                {
                    b.Navigation("Kdmtthdnks");
                });

            modelBuilder.Entity("BuildCongRenLuyen.Models.Sdmlop", b =>
                {
                    b.Navigation("KdmlichDangKies");

                    b.Navigation("Sdmsvs");
                });

            modelBuilder.Entity("BuildCongRenLuyen.Models.Sdmsv", b =>
                {
                    b.Navigation("Kkqsvdkhdnks");
                });
#pragma warning restore 612, 618
        }
    }
}
